version: '3.8'

services:
  db:
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER={{ cookiecutter.project_name }}
      - POSTGRES_PASSWORD=${{ cookiecutter.project_name.upper() }}_DB_PASSWORD
      - POSTGRES_DB={{ cookiecutter.project_name }}

  api:
    depends_on:
      - db
    build: .
    environment:
      - DB_CONNECTION_URL={{ cookiecutter.dburl }}
    ports:
      - 8000:80

  migration:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.migrations
    command: >
      sh -c "sleep 5 &&
            poetry run alembic upgrade head"
    environment:
      - DB_CONNECTION_URL={{ cookiecutter.dburl }}
    volumes:
      - .:/tmp